iggyray/mercari-build-hackathon-2023

.github/workflows/build.yml, backend/db/repository.go, backend/go.mod, backend/handler/handler.go, backend/main.go
Created `initialise` branch and Initialised repo
=> Initialised repo

backend/sql/01_schema.sql
What:
- Edited DB schema to automatically insert default categories on db creation
=> Edited DB schema

backend/sql/01_schema.sql
Changes:
- made `name` column in `user` table `NOT NULL` `UNIQUE`
- So that users can log in with their unique user name instead of ID
=> Refactor user table schema to enable username login

frontend/simple-mercari-web/package-lock.json, frontend/simple-mercari-web/package.json, frontend/simple-mercari-web/public/index.html, frontend/simple-mercari-web/src/components/Listing/Listing.tsx
Changes:
- installed bootstrap dependency
- Styled listing page to test that bootstrap css works
=> Installed bootstrap dependency

frontend/simple-mercari-web/package-lock.json, frontend/simple-mercari-web/package.json, frontend/simple-mercari-web/public/index.html, frontend/simple-mercari-web/src/App.css, frontend/simple-mercari-web/src/components/Home/Home.tsx, frontend/simple-mercari-web/src/components/Listing/Listing.tsx
Changes:
- Made either login/ signup component show depending on state `isLogInPage`
- Created a button under each component to toggle the state
=> Toggle login/ signup pages (Merge after #7)

backend/domain/user.go
Changes:
- Added receiver function `validate` in user domain so that user name can be validated easily
=> Add validations to user domain

backend/db/repository.go, backend/handler/handler.go, frontend/simple-mercari-web/src/components/Login/Login.tsx, frontend/simple-mercari-web/src/components/Signup/Signup.tsx
Changes:
Frontend:
- Changed frontend login page, to take username input instead of id
- Changed body of POST request to login endpoint to include name instead of id
Backend
- Added a `GetUserByName` function to repo to get user by `name` instead of `id`
- Changed handler to use new `GetUserByName` function
=> Login with username instead of id

backend/db/repository.go, backend/handler/handler.go, frontend/simple-mercari-web/src/App.css, frontend/simple-mercari-web/src/components/Home/Home.tsx, frontend/simple-mercari-web/src/components/Item/Item.tsx, frontend/simple-mercari-web/src/components/Login/Login.tsx, frontend/simple-mercari-web/src/components/Signup/Signup.tsx
Changes:
- Simplify listed items on main page & profile page to only display price and name
=> Simplify Item.tsx display

backend/db/repository.go, backend/handler/handler.go, backend/main.go
Changes: 
Backend:
- added `/search` endpoint in `main.go`
- added  `SearchItems` function in `handler.go` to handle endpoint logic
- added new type `getItemsResponse` in consideration of future dev features
- added `GetItemsByKeyword` function in `repository.go` to fetch data from db if `item name` matches `keyword` pattern
=> Backend: /search endpoint implementation

frontend/simple-mercari-web/src/App.css, frontend/simple-mercari-web/src/components/Home/Home.tsx, frontend/simple-mercari-web/src/components/SearchBar/SearchBar.tsx, frontend/simple-mercari-web/src/components/SearchBar/index.tsx
Changes:
Frontend:
- Created `SearchBar` component
- Used `Searchbar` in `Home` component (temp: to refactor in the future)
- Enabled `SearchBar` child to pass data to parent `Home` component
- Hooked up `Home` to backend `/search` endpoint
=> Frontend: Search bar implementation (merge after #14)

backend/README.md, backend/domain/item.go, backend/handler/handler.go, frontend/simple-mercari-web/src/components/ItemDetail/ItemDetail.tsx
Changes:
- Day 2 Updates from main repo
=> Day 2 Updates from main repo

frontend/simple-mercari-web/src/components/Header/Header.tsx, frontend/simple-mercari-web/src/components/Home/Home.tsx, frontend/simple-mercari-web/src/components/Login/Login.tsx
Add userName to Cookies
Change display id to name
=> Change display id to name

frontend/simple-mercari-web/src/components/Header/Header.tsx, frontend/simple-mercari-web/src/components/ItemDetail/ItemDetail.tsx, frontend/simple-mercari-web/src/components/Listing/Listing.tsx, frontend/simple-mercari-web/src/components/SignInSignUp/SignInSignUp.tsx
- Edit logic to check login or not
- Redirect login page to my page if already login
- Redirect purchase button to login page if not already login
- Redirect sell page to login page if not already login
=> Edit redirection

frontend/simple-mercari-web/src/App.css, frontend/simple-mercari-web/src/components/ItemDetail/ItemDetail.tsx
Changes:
Frontend:
- Added some simple styling to item detail page
=> Frontend: Style Item Detail Page

backend/handler/handler.go, frontend/simple-mercari-web/src/components/UserProfile/UserProfile.tsx
- Add error if balance is less than zero
=> Add error if balance is less than zero

backend/sql/01_schema.sql
Changes:
Backend:
- Removed query to insert items into db to fix initialize
=> Fix initialize

backend/db/repository.go, backend/handler/handler.go
Changes:
Backend:
- Restore default register response (for benchmark score)
=> Debug: Restore default register response

backend/sql/01_schema.sql
Changes:
Backend:
- created schema for comment table
=> Backend: Schema for comment table

frontend/simple-mercari-web/src/components/Header/Header.css, frontend/simple-mercari-web/src/components/Header/Header.tsx, frontend/simple-mercari-web/src/components/ItemDetail/ItemDetail.tsx, frontend/simple-mercari-web/src/components/Listing/Listing.tsx, frontend/simple-mercari-web/src/components/SignInSignUp/SignInSignUp.tsx
- Condense logout and my page to Account
=> Condense logout and my page to Account

frontend/simple-mercari-web/src/App.css, frontend/simple-mercari-web/src/components/Item/Item.tsx, frontend/simple-mercari-web/src/components/ItemList/ItemList.tsx, frontend/simple-mercari-web/src/components/UserProfile/UserProfile.tsx
Changes:
Frontend:
- Applied grid layout to app (design to be refined in future)
- Minor css changes in `item detail.tsx` & `item.tsx`
=> Frontend: Grid Layout

backend/db/repository.go, backend/handler/handler.go, backend/main.go, frontend/simple-mercari-web/src/App.css, frontend/simple-mercari-web/src/components/Header/Header.tsx, frontend/simple-mercari-web/src/components/Home/Home.tsx, frontend/simple-mercari-web/src/components/Item/Item.tsx, frontend/simple-mercari-web/src/components/ItemList/ItemList.tsx, frontend/simple-mercari-web/src/components/Login/Login.tsx, frontend/simple-mercari-web/src/components/SignInSignUp/SignInSignUp.tsx, frontend/simple-mercari-web/src/components/Signup/Signup.tsx, frontend/simple-mercari-web/src/components/UserProfile/UserProfile.tsx
- Add PUT function
- Create UpdateItem in repository.go
- Create UpdateItem in handler.go
=> Backend Update Item

backend/db/repository.go, backend/handler/handler.go, backend/main.go, frontend/simple-mercari-web/src/components/ItemDetail/ItemDetail.tsx
- User cannot buy own items
- User cannot buy items that have price more than balance
- User cannot buy sold items
=> Backend purchase item (Merge after #38)

backend/db/repository.go, backend/domain/comment.go, backend/handler/handler.go, backend/main.go, backend/sql/01_schema.sql
Changes:
Backend:
- Created `Comment` domain
- Created `Comment Repo` with `addComment` and `getComment` functions
- Created `/comments` endpoint
=> Backend: Comment Implementation (merge after #29)

frontend/simple-mercari-web/src/components/ItemDetail/ItemDetail.tsx
Changes:
Frontend:
- Created `edit listing` button in item listing
- Added `buttonType` state to manage the display of purchase/ sold out/ edit buttons
=> Frontend: item listing edit button

backend/db/repository.go, backend/main.go, frontend/simple-mercari-web/src/App.css, frontend/simple-mercari-web/src/components/Comment/Comment.tsx, frontend/simple-mercari-web/src/components/Comment/index.tsx, frontend/simple-mercari-web/src/components/CommentBoard/CommentBoard.tsx, frontend/simple-mercari-web/src/components/CommentBoard/index.tsx, frontend/simple-mercari-web/src/components/ItemDetail/ItemDetail.tsx
Changes:
Backend:
- debugged `commentRepository`
Frontend:
- Created `Comment` component
- Created `CommentBoard` component
- Hooked frontend to backend endpoints
TODO:
- Styling of `CommentBoard`
- Refactor backend to save `user_name` when comment is added
=> Frontend: Comment Component Implementation

backend/db/repository.go, backend/handler/handler.go, frontend/simple-mercari-web/src/components/Signup/Signup.tsx
=> Get image validation (Merge after #47)

backend/db/repository.go, backend/domain/comment.go, backend/handler/handler.go, backend/sql/01_schema.sql, frontend/simple-mercari-web/src/components/CommentBoard/CommentBoard.tsx, frontend/simple-mercari-web/src/components/ItemDetail/ItemDetail.tsx
Changes:
- Extended `Comment` definitions where needed in frontend and backend
- Maintained current comment functionality
=> Extend Comments to include parent comment id

frontend/simple-mercari-web/src/App.css
Changes:
Frontend:
- fix overflowing desription on `ItemDetail` page
=> Debug: Overflowing description

backend/handler/handler.go, frontend/simple-mercari-web/src/components/Listing/Listing.tsx
- Limit image size
- Handing image size error
=> Limit image size

frontend/simple-mercari-web/src/App.css, frontend/simple-mercari-web/src/components/UserProfile/UserProfile.tsx
Changes:
Frontend:
- added some styling to profile page
=> Frontend: Style Profile Page

frontend/simple-mercari-web/src/App.css, frontend/simple-mercari-web/src/components/ItemDetail/ItemDetail.tsx
- Made elements slightly more spread out to decrease clutter
=> Frontend: Style Item Detail

frontend/simple-mercari-web/src/components/ItemDetail/ItemDetail.tsx
Changes:
Frontend:
- when a user that is not logged in tries to comment/ reply to a comment, they will be redirected to login page
=> Prevent submit comment/ reply without login

frontend/simple-mercari-web/src/App.css, frontend/simple-mercari-web/src/components/Item/Item.tsx
Changes:
Frontend:
- add sold tag when item is sold on listing page
=> Add Sold Tag

backend/db/repository.go, backend/handler/handler.go, backend/main.go, frontend/simple-mercari-web/src/components/Home/Home.tsx
Changes:
- change /item endpoint to not return item status 1 items
- changed our own /itemv2 endpoint to not return status 1 items
=> Debug GET items
